spring:
  security:
    oauth2:
      client:
        registration:
#          my-client-1:
#            client-id: "client-1"
#            client-secret: "password"
#            client-name: "Client for user scope"
#            provider: "my-oauth-provider"
#            scope: "BROWSER"
#            redirect-uri: "http://localhost:8080"
#            client-authentication-method: "basic"
#            authorization-grant-type: "password"
          my-client-2:
            client-id: "client-1"
            client-secret: "password"
            client-name: "Client for BROWSER scope"
            provider: "my-oauth-provider"
            scope: "BROWSER"
            redirect-uri: "https://localhost:8080"
            client-authentication-method: "basic"
            authorization-grant-type: "password"
        provider:
          my-oauth-provider:
            authorization-uri: "http://localhost:8000/oauth/authorize"
            token-uri: "http://localhost:8000/oauth/token"
            user-info-uri: "http://localhost:8000/userinfo"
            user-info-authentication-method: "header"
            jwk-set-uri: "http://localhost:8000/token_keys"
            user-name-attribute: "name"

