server:
  port: 8000
#spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: "https://example.com/oauth2/default/v1/keys"
#          issuer-uri: "https://dev-123456.oktapreview.com/oauth2/default/"
#          public-key-location:

#spring:
#  security:
#    oauth2:
#      resourceserver:
#        opaquetoken:
#          introspection-uri: "https://example.com/check-token"
#          client-id: "my-client-id"
#          client-secret: "my-client-secret"


spring:
  redis:
    port: 6379
    host: 8.136.96.34
    password: afD60y3e
    jedis:
      pool:
        max-active: 8
        max-wait: 10000ms
        min-idle: 1
    timeout: 10000ms
    database: 12

